-- Migration: Create MGE (Mightiest Governor Event) tables
-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)

-- MGE Events
CREATE TABLE IF NOT EXISTS public.mge_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_date date NOT NULL,
  focused_commander text NOT NULL,
  notes text,
  is_published boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS mge_events_date_idx ON public.mge_events(event_date DESC);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION public.mge_events_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS mge_events_updated_at_trigger ON public.mge_events;
CREATE TRIGGER mge_events_updated_at_trigger
  BEFORE UPDATE ON public.mge_events
  FOR EACH ROW EXECUTE FUNCTION public.mge_events_updated_at();

-- MGE Selections (who is assigned to which ranking tier)
CREATE TABLE IF NOT EXISTS public.mge_selections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mge_event_id bigint NOT NULL REFERENCES public.mge_events(id) ON DELETE CASCADE,
  member_name text NOT NULL,
  ranking_tier text NOT NULL DEFAULT 'Top 10',
  power_cap bigint,
  reason text,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),

  UNIQUE(mge_event_id, member_name)
);

CREATE INDEX IF NOT EXISTS mge_selections_event_idx ON public.mge_selections(mge_event_id);

-- RLS: public read/write (admin gated at UI level)
ALTER TABLE public.mge_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mge_selections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read" ON public.mge_events FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.mge_events FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.mge_events FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.mge_events FOR DELETE USING (true);

CREATE POLICY "Allow public read" ON public.mge_selections FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.mge_selections FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.mge_selections FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.mge_selections FOR DELETE USING (true);

-- ─── Migration: Application System ─────────────────────────────────

-- Add new columns to mge_events
ALTER TABLE public.mge_events
  ADD COLUMN IF NOT EXISTS application_deadline timestamptz,
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'draft';

-- MGE Event Commanders (structured replacement for focused_commander text)
CREATE TABLE IF NOT EXISTS public.mge_event_commanders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mge_event_id bigint NOT NULL REFERENCES public.mge_events(id) ON DELETE CASCADE,
  commander_name text NOT NULL,
  is_focus boolean NOT NULL DEFAULT false,
  sort_order int NOT NULL DEFAULT 0,
  UNIQUE(mge_event_id, commander_name)
);

-- MGE Rank Tiers (admin-defined rank structure with point caps)
CREATE TABLE IF NOT EXISTS public.mge_rank_tiers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mge_event_id bigint NOT NULL REFERENCES public.mge_events(id) ON DELETE CASCADE,
  tier_label text NOT NULL,
  point_cap bigint,
  is_ffa boolean NOT NULL DEFAULT false,
  sort_order int NOT NULL DEFAULT 0,
  UNIQUE(mge_event_id, tier_label)
);

-- MGE Applications (player submissions with commander stats)
CREATE TABLE IF NOT EXISTS public.mge_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mge_event_id bigint NOT NULL REFERENCES public.mge_events(id) ON DELETE CASCADE,
  applicant_name text NOT NULL,
  applicant_alliance text,
  applicant_power bigint,
  commander_name text NOT NULL,
  commander_level int,
  skill_levels int[],
  commander_stars int,
  preferred_tier text,
  max_tier text,
  notes text,
  status text NOT NULL DEFAULT 'pending',
  officer_notes text,
  assigned_tier text,
  decided_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(mge_event_id, applicant_name)
);

-- RLS for new tables
ALTER TABLE public.mge_event_commanders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mge_rank_tiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mge_applications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read" ON public.mge_event_commanders FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.mge_event_commanders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.mge_event_commanders FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.mge_event_commanders FOR DELETE USING (true);

CREATE POLICY "Allow public read" ON public.mge_rank_tiers FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.mge_rank_tiers FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.mge_rank_tiers FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.mge_rank_tiers FOR DELETE USING (true);

CREATE POLICY "Allow public read" ON public.mge_applications FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.mge_applications FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.mge_applications FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.mge_applications FOR DELETE USING (true);

-- ─── Migration: Screenshot uploads ──────────────────────────────────
-- Add screenshot_url column to mge_applications
ALTER TABLE public.mge_applications ADD COLUMN IF NOT EXISTS screenshot_url text;

-- Create storage bucket for MGE screenshots (run in Supabase Dashboard > Storage):
-- 1. Create bucket named "mge-screenshots" with public access
-- 2. Or run this SQL:
INSERT INTO storage.buckets (id, name, public) VALUES ('mge-screenshots', 'mge-screenshots', true)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS policies for mge-screenshots bucket
CREATE POLICY "Allow public upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'mge-screenshots');
CREATE POLICY "Allow public read" ON storage.objects FOR SELECT USING (bucket_id = 'mge-screenshots');

-- ─── Migration: Equipment rating & reward heads ─────────────────────
-- Officer-assigned equipment rating (0-10) based on screenshot evaluation
ALTER TABLE public.mge_applications
  ADD COLUMN IF NOT EXISTS equipment_rating smallint;

-- Gold head rewards per rank tier
ALTER TABLE public.mge_rank_tiers
  ADD COLUMN IF NOT EXISTS reward_heads int;
