-- Migration: Create rok_mail table for shareable mail drafts
-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)

CREATE TABLE IF NOT EXISTS public.rok_mail (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  share_id text UNIQUE NOT NULL,
  name text DEFAULT 'Untitled Mail',
  content text DEFAULT '',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Index for fast share_id lookups
CREATE INDEX IF NOT EXISTS rok_mail_share_id_idx ON public.rok_mail(share_id);

-- Auto-update updated_at on changes
CREATE OR REPLACE FUNCTION public.rok_mail_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS rok_mail_updated_at_trigger ON public.rok_mail;
CREATE TRIGGER rok_mail_updated_at_trigger
  BEFORE UPDATE ON public.rok_mail
  FOR EACH ROW EXECUTE FUNCTION public.rok_mail_updated_at();

-- RLS: allow public read/write (no auth required, same as aoo_strategy)
ALTER TABLE public.rok_mail ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read" ON public.rok_mail
  FOR SELECT USING (true);

CREATE POLICY "Allow public insert" ON public.rok_mail
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update" ON public.rok_mail
  FOR UPDATE USING (true);
